version: "3"

services:
  redis:
    image: redis:6.2.5-alpine
    container_name: ai_test_redis
    restart: always
    volumes:
    - ./docker_config/redis.conf:/etc/redis/redis.conf
    ports:
    - "6379"
    command: redis-server /etc/redis/redis.conf

  uvicorn:
    build:
      context: .
      dockerfile: pythonDockerfile
    image: ai_test_uvicorn:v1
    container_name: "ai_test_uvicorn"
    restart: always
    ports:
      - "8080"
    environment:
      - DB_USER=root
      - DB_PWD=root1234
      - DB_HOST=ai_test_mysql
      - REDIS_HOST=ai_test_redis
      - REDIS_PROT=6379
    depends_on:
      - redis
      - mysql
    command: ["uvicorn", "backstage_main:app", "--host", "0.0.0.0", "--port", "8080"]

  celery:
      build:
        context: .
        dockerfile: pythonDockerfile
      image: ai_test_celery:v1
      container_name: "ai_test_celery"
      restart: always
      environment:
        - DB_USER=root
        - DB_PWD=root1234
        - DB_HOST=ai_test_mysql
        - REDIS_HOST=ai_test_redis
        - REDIS_PROT=6379
      depends_on:
        - redis
        - mysql
      # python3 scripts/create_demo_data.py &&
      command: celery -A celery_main:app worker -c 1 -l INFO

  nginx:
    build:
      context: .
      dockerfile: frontedDockerfile
    image: ai_test_nginx:v1
    container_name: "ai_test_nginx"
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - uvicorn
      - celery

  mysql:
    image: mysql:5.7
    container_name: ai_test_mysql
    restart: always
    user: "0"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: test_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - "3306"
    volumes:
    - ./output/mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
