# -*- coding: utf-8 -*-
from sqlalchemy import Column, Integer, String, SmallInteger, Text, Float, DateTime, text, JSON

from . import Base


class case_bank_card(Base):
    __tablename__ = "case_bank_card"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    code = Column(String(255), comment='银行卡号')
    remark = Column(String(255))
    enabled = Column(SmallInteger, default=1, comment='1 激活 0 禁用')


class case_captcha(Base):
    __tablename__ = "case_captcha"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    code = Column(String(255), comment="验证码")
    type = Column(String(255), comment="类型")
    remark = Column(String(255))
    enabled = Column(SmallInteger, default=1)


class case_car_angle(Base):
    __tablename__ = "case_car_angle"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    car_angle = Column(SmallInteger, comment="{'abnormal': 0, 'F': 1, 'FS': 2, 'R': 3, 'RS': 4, 'S': 5, }")
    inputer = Column(String(255))
    batch = Column(String(255))


class case_car_in_pic(Base):
    __tablename__ = "case_car_in_pic"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    is_car = Column(String(255))
    remark = Column(String(255))
    batch = Column(String(255))


class case_cdas_accident_car(Base):
    __tablename__ = "case_cdas_accident_car"
    id = Column(Integer, primary_key=True, autoincrement=True)
    order_code = Column(String(255))
    vin = Column(String(255))
    insure = Column(Text)
    mtnc = Column(Text)
    is_accident = Column(SmallInteger, comment="1 事故车；0 非事故车")
    check_tab_id = Column(Integer, comment="1 通用；2 平安")
    invalid_state = Column(SmallInteger, comment="0:非无效;-1无法确认事故情况;-2无需修改;-3暂无法确认")
    car_type = Column(SmallInteger, comment="0 正常车；1 泡水车；2 火烧车; 3 泡水+火烧")
    sid = Column(String(255), comment="特殊车型 sid")
    year = Column(String(255), comment="年款")
    model_price = Column(Float, comment="车型指导价")
    pd_reason_mtnc = Column(Text, comment="""维保判定原因和时间   {"记录时间": "判定原因",}""")
    pd_reason_insure = Column(Text, comment="""保险判定原因和时间   {"记录时间": "判定原因",}""")
    remark = Column(String(255))
    create_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    update_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    batch = Column(String(255))
    enabled = Column(SmallInteger)


class case_cdas_car_comp(Base):
    __tablename__ = "case_cdas_car_comp"
    id = Column(Integer, primary_key=True, autoincrement=True)
    order_code = Column(String(255))
    vin = Column(String(255))
    sid = Column(String(255), comment="特殊车型 sid")
    year = Column(String(255), comment="年款")
    record_id = Column(String(255), comment="cdas记录id")
    data = Column(JSON, comment="拼凑的小条记录,维保或者保险")
    comp_action = Column(Text, comment="所有部件和动作的json, [[comp,action],]")
    classify = Column(JSON, comment="归类类型")
    add_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    update_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    batch = Column(String(255))
    remark = Column(String(255))


class case_classify_pic(Base):
    __tablename__ = "case_classify_pic"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    local_pic_url = Column(String(255))
    classify = Column(SmallInteger, comment="图片分类{'0':'车','1':'登记证正面','2':'登记证反面','3':'行驶证','4':'铭牌','5':'挡风玻璃',"
                                            "'6':'其他不相关图片','7':'合格证'}")
    remark = Column(String(255))
    batch = Column(String(255))


class case_daben_back(Base):
    __tablename__ = "case_daben_back"
    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(Text)
    local_pic_url = Column(Text)
    mortgage_register = Column(JSON, comment="抵押登记")
    transfer_register = Column(JSON, comment="转移登记")
    change_record = Column(JSON, comment="变更备案")
    remark = Column(JSON, comment="备注")
    reissue = Column(JSON, comment="补领登记证书")
    discharge_mortgage = Column(JSON, comment="解除抵押")
    change_register = Column(JSON, comment="变更登记")
    exchange = Column(JSON, comment="换领登记证书")
    cancel_mortgage = Column(JSON, comment="注销抵押")
    discharge_pledge_record = Column(JSON, comment="解除质押备案")
    correction = Column(JSON, comment="登记事项更正")
    pledge_record = Column(JSON, comment="质押备案")
    serial_number = Column(String(255), comment="机动车登记证书编号")
    endorse_delete = Column(JSON, comment="签注作废")
    guo_hu_deng_ji = Column(JSON, comment="过户登记")
    djsxzf = Column(JSON, comment="登记事项作废")
    batch = Column(String(255))
    inputer = Column(String(255))
    enabled = Column(SmallInteger)
    created_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))


class case_daben_front(Base):
    __tablename__ = "case_daben_front"
    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(String(255))
    local_pic_url = Column(String(255))
    driving_license_number = Column(String(255), comment="登记证编号")
    tire_spec = Column(String(255), comment="轮胎规格")
    vehicle_date_manufacture = Column(String(255), comment="车辆出厂日期")
    maker_type = Column(String(255), comment="国产/进口")
    engine = Column(String(255), comment="发动机号")
    plate_number = Column(String(255), comment="机动车登记编号")
    car_type = Column(String(255), comment="车辆类型")
    color = Column(String(255), comment="车身颜色")
    owner_card_type_number = Column(String(255), comment="机动车所有人/身份证明名称/号码")
    vin = Column(String(255))
    fuel_type = Column(String(255), comment="燃料种类")
    model = Column(String(255), comment="车辆型号")
    reg_authority = Column(String(255), comment="登记机关")
    reg_date = Column(String(255), comment="登记日期")
    brand = Column(String(255), comment="车辆品牌")
    page = Column(String(255), comment="所在页码")
    transfer_reg_summary = Column(JSON, comment="转移登记摘要")
    stamp = Column(String(255), comment="是否盖章")
    serial_number = Column(String(255), comment="编号")
    use_type = Column(String(255), comment="使用性质")
    seats = Column(String(255), comment="核定载客")
    tire_num = Column(String(255), comment="轮胎数")
    clhdfs = Column(String(255), comment="车辆获得方式")
    inputer = Column(String(255), comment="录入人")
    engine_code = Column(String(255), comment="发动机型号")
    liter = Column(String(255), comment="排量")
    manufacturer = Column(String(255), comment="制造厂")
    steer_type = Column(String(255), comment="转向形式")
    front_tread = Column(String(255), comment="前轮距")
    rear_tread = Column(String(255), comment="后轮距")
    springs_leaf_num = Column(String(255), comment="钢板弹簧片数")
    wheel_base = Column(String(255), comment="轴距")
    n_axles = Column(String(255), comment="轴数")
    outside_size = Column(String(255), comment="外廓尺寸")
    cargo_size = Column(String(255), comment="货厢内部尺寸")
    gross_weight = Column(String(255), comment="总质量")
    rate_weight = Column(String(255), comment="核定载质量")
    traction_weight = Column(String(255), comment="准牵引质量")
    cab_n_seats = Column(String(255), comment="驾驶室载客数")
    certificate_office = Column(String(255), comment="发证机关")
    certificate_date = Column(String(255), comment="发证日期")
    batch = Column(String(255))
    enabled = Column(SmallInteger)
    created_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))


class case_daben_half(Base):
    __tablename__ = "case_daben_half"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    active_key = Column(JSON, comment="半页中存在的字段")
    driving_license_number = Column(String(255), comment="登记证编号")
    tire_spec = Column(String(255), comment="轮胎规格")
    vehicle_date_manufacture = Column(String(255), comment="车辆出厂日期")
    maker_type = Column(String(255), comment="国产/进口")
    engine = Column(String(255), comment="发动机号")
    plate_number = Column(String(255), comment="机动车登记编号")
    car_type = Column(String(255), comment="车辆类型")
    color = Column(String(255), comment="车身颜色")
    owner_card_type_number = Column(String(255), comment="机动车所有人/身份证明名称/号码")
    vin = Column(String(255))
    fuel_type = Column(String(255), comment="燃料种类")
    model = Column(String(255), comment="车辆型号")
    reg_authority = Column(String(255), comment="登记机关")
    reg_date = Column(String(255), comment="登记日期")
    brand = Column(String(255), comment="车辆品牌")
    page = Column(String(255), comment="所在页码")
    transfer_reg_summary = Column(JSON, comment="转移登记摘要")
    stamp = Column(String(255), comment="是否盖章")
    use_type = Column(String(255), comment="使用性质")
    seats = Column(String(255), comment="核定载客")
    tire_num = Column(String(255), comment="轮胎数")
    clhdfs = Column(String(255), comment="车辆获得方式")
    inputer = Column(String(255), comment="录入人")
    engine_code = Column(String(255), comment="发动机型号")
    liter = Column(String(255), comment="排量")
    manufacturer = Column(String(255), comment="制造厂")
    steer_type = Column(String(255), comment="转向形式")
    front_tread = Column(String(255), comment="前轮距")
    rear_tread = Column(String(255), comment="后轮距")
    springs_leaf_num = Column(String(255), comment="钢板弹簧片数")
    wheel_base = Column(String(255), comment="轴距")
    n_axles = Column(String(255), comment="轴数")
    outside_size = Column(String(255), comment="外廓尺寸")
    cargo_size = Column(String(255), comment="货厢内部尺寸")
    gross_weight = Column(String(255), comment="总质量")
    rate_weight = Column(String(255), comment="核定载质量")
    traction_weight = Column(String(255), comment="准牵引质量")
    cab_n_seats = Column(String(255), comment="驾驶室载客数")
    certificate_office = Column(String(255), comment="发证机关")
    certificate_date = Column(String(255), comment="发证日期")
    mortgage_register = Column(JSON, comment="抵押登记")
    transfer_register = Column(JSON, comment="转移登记")
    change_record = Column(JSON, comment="变更备案")
    remark = Column(JSON, comment="备注")
    reissue = Column(JSON, comment="补领登记证书")
    discharge_mortgage = Column(JSON, comment="解除抵押")
    change_register = Column(JSON, comment="变更登记")
    exchange = Column(JSON, comment="换领登记证书")
    cancel_mortgage = Column(JSON, comment="注销抵押")
    discharge_pledge_record = Column(JSON, comment="解除质押备案")
    correction = Column(JSON, comment="登记事项更正")
    pledge_record = Column(JSON, comment="质押备案")
    serial_number = Column(String(255), comment="机动车登记证书编号")
    endorse_delete = Column(JSON, comment="签注作废")
    guo_hu_deng_ji = Column(JSON, comment="过户登记")
    djsxzf = Column(JSON, comment="登记事项作废")
    enabled = Column(SmallInteger)
    created_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))


class case_fanpai(Base):
    __tablename__ = "case_fanpai"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    type = Column(SmallInteger, comment="1:翻拍（电脑屏幕） 0:原始图片")
    remark = Column(String(255))
    enabled = Column(String(255))


class case_id_card(Base):
    __tablename__ = "case_id_card"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    name = Column(String(255))
    sex = Column(String(255))
    nation = Column(String(255))
    birthdate = Column(String(255))
    address = Column(String(255))
    identity_number = Column(String(255))
    issuing_authority = Column(String(255), comment="签发机关")
    expiry_date = Column(String(255), comment="有效期限")
    remark = Column(String(255))
    enabled = Column(SmallInteger)


class case_mile(Base):
    __tablename__ = "case_mile"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    local_pic_url = Column(String(255))
    mile = Column(String(255), comment="里程数，单位：km")
    remark = Column(String(255))
    batch = Column(String(255))


class case_nameplate(Base):
    __tablename__ = "case_nameplate"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    vin = Column(String(255))
    remark = Column(String(255))
    batch = Column(String(255))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    enabled = Column(SmallInteger)


class case_purchase_invoice(Base):
    __tablename__ = "case_purchase_invoice"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    file_name = Column(String(255))
    kai_piao_ri_qi = Column(String(255), comment="开票日期")
    fa_piao_dai_ma = Column(String(255), comment="发票代码")
    fa_piao_hao_ma = Column(String(255), comment="发票号码")
    ji_da_dai_ma = Column(String(255), comment="机打代码")
    ji_da_hao_ma = Column(String(255), comment="机打号码")
    ji_qi_bian_hao = Column(String(255), comment="机器编号")
    gou_mai_fang_ming_cheng = Column(String(255), comment="购买方名称")
    sfzhmhzzjgdm = Column(String(255), comment="身份证号码或组织机构代码")
    che_liang_lei_xing = Column(String(255), comment="车辆类型")
    chang_pai_xing_hao = Column(String(255), comment="厂牌型号")
    chan_di = Column(String(255), comment="产地")
    he_ge_zheng_hao = Column(String(255), comment="合格证号")
    jkzmsh = Column(String(255), comment="进口证明书号")
    shang_jian_dan_hao = Column(String(255), comment="商检单号")
    fa_dong_ji_hao_ma = Column(String(255), comment="发动机号码")
    vin = Column(String(255))
    jshjdx = Column(String(255), comment="价税合计大写")
    jshjxx = Column(String(255), comment="价税合计小写")
    xhdwmc = Column(String(255), comment="销货单位名称")
    dian_hua = Column(String(255), comment="电话")
    nsrsbh = Column(String(255), comment="纳税人识别号")
    zhang_hao = Column(String(255), comment="账号")
    di_zhi = Column(String(255), comment="地址")
    kai_hu_yin_hang = Column(String(255), comment="开户银行")
    zzsslhzsl = Column(String(255), comment="增值税税率或征收率")
    zeng_zhi_shui_shui_e = Column(String(255), comment="增值税税额")
    zgswjgdm = Column(String(255), comment="主管税务机关代码")
    zgswjg = Column(String(255), comment="主管税务机关")
    bu_han_shui_jia = Column(String(255), comment="不含税价")
    wspzhm = Column(String(255), comment="完税凭证号码")
    dun_wei = Column(String(255), comment="吨位")
    xian_cheng_ren_shu = Column(String(255), comment="限乘人数")
    kai_piao_ren = Column(String(255), comment="开票人")
    batch = Column(String(255))


class case_vehicle_license(Base):
    __tablename__ = "case_vehicle_license"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    pic_url_cut = Column(String(255))
    local_pic_url = Column(String(255))
    local_pic_url_cut = Column(String(255))
    vin = Column(String(255))
    plate_no = Column(String(255), comment="车牌号")
    engine_no = Column(String(255), comment="发动机号码")
    register_date = Column(String(255), comment="注册日期")
    vehicle_type = Column(String(255), comment="车辆类型")
    owner = Column(String(255), comment="所有者")
    address = Column(String(255), comment="住址")
    model = Column(String(255), comment="品牌型号")
    notice_model = Column(String(255), comment="查询数据库更正后model")
    use_character = Column(String(255), comment="使用性质")
    issue_date = Column(String(255), comment="发证日期")
    level = Column(String(255), comment="每个字段困难度")
    inputer = Column(String(255), comment="录入人")
    batch = Column(String(255))
    flag = Column(SmallInteger, comment="-1: model不全")
    created_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))


class case_vehicle_plate(Base):
    __tablename__ = "case_vehicle_plate"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    car_number = Column(String(255), comment="车牌号码")
    plate_color = Column(String(255), comment="车牌颜色")
    inputer = Column(String(255), comment="录入人")
    batch = Column(String(255))


class case_vehicle_qualification(Base):
    __tablename__ = "case_vehicle_qualification"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    number = Column(String(255), comment="合格证编号")
    issue_date = Column(String(255), comment="发证日期")
    manufacturer = Column(String(255), comment="车辆制造企业名称")
    brand_type = Column(String(255), comment="车辆品牌/车辆名称")
    model = Column(String(255), comment="车辆型号")
    vin = Column(String(255))
    color = Column(String(255), comment="车身颜色")
    chassis_model_chassis_id = Column(String(255), comment="底盘型号/底盘ID")
    chassis_num = Column(String(255), comment="底盘合格证编号")
    engine_model = Column(String(255), comment="发动机型号")
    engine_num = Column(String(255), comment="发动机号")
    fuel_type = Column(String(255), comment="燃料种类")
    engine_capacity_engine_power = Column(String(255), comment="排量和功率（ml/kW）")
    emission_standard = Column(String(255), comment="排放标准")
    fuel_consumption = Column(String(255), comment="油耗")
    outer_size = Column(String(255), comment="外廓尺寸(mm)")
    inner_size = Column(String(255), comment="货箱内部尺寸")
    number_of_leaf_springs = Column(String(255), comment="钢板弹簧片数")
    tyre_num = Column(String(255), comment="轮胎数")
    tyre_size = Column(String(255), comment="轮胎规格")
    wheel_track = Column(String(255), comment="轮距")
    wheel_base = Column(String(255), comment="轴距")
    axle_load = Column(String(255), comment="轴荷")
    axle_number = Column(String(255), comment="轴数")
    steering_mode = Column(String(255), comment="转向形式")
    total_mass = Column(String(255), comment="总重量")
    curb_weight = Column(String(255), comment="整备质量")
    rated_load = Column(String(255), comment="额定载质量")
    utilization_factor_of_payload = Column(String(255), comment="载质量利用系数")
    tow_weight = Column(String(255), comment="准牵引总质量")
    total_mass_semi_trailer = Column(String(255), comment="半挂车鞍座最大允许总质量")
    cab_passengers = Column(String(255), comment="驾驶室准乘人数")
    rated_passengers = Column(String(255), comment="额定载客")
    max_speed = Column(String(255), comment="最高设计车速(km/h)")
    manufacture_date = Column(String(255), comment="车辆制造日期")
    remark = Column(String(255))
    enabled = Column(SmallInteger)


class case_vin(Base):
    __tablename__ = "case_vin"
    id = Column(Integer, primary_key=True, autoincrement=True)
    pic_url = Column(String(255))
    type = Column(String(255), comment="类型")
    vin = Column(String(255), comment="车架号")
    remark = Column(String(255))
    created_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
    updated_time = Column(DateTime, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    enabled = Column(SmallInteger)
